/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controladores.ControladorVolverMenuPrincipal;
import controladores.Profesionales.ControladorMisTurnosProf;

/**
 *
 * @author Silvia
 */
public class MenuProfesionales extends javax.swing.JFrame {

    /**
     * Creates new form profesionales
     */
    public MenuProfesionales() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("PROFESIONALES");
        
       controladorEstadoTurnoPr =new ControladorMisTurnosProf();
        botEstadoTurnos.addMouseListener(controladorEstadoTurnoPr );
           
        controladorRegresar = new ControladorVolverMenuPrincipal();
        botMenuPrincipal.addMouseListener(controladorRegresar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botMenuPrincipal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botEstadoTurnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/volver.gif"))); // NOI18N
        botMenuPrincipal.setText("VOLVER A MENU PRINCIPAL");
        botMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(botMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 110, 110));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("PROFESIONALES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 330, 60));

        botEstadoTurnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botEstadoTurnos.setText("ESTADO DE TURNOS");
        botEstadoTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEstadoTurnosActionPerformed(evt);
            }
        });
        getContentPane().add(botEstadoTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 400, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/A-GUARDAPOLVO-MEDIC.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMenuPrincipalActionPerformed
       
    }//GEN-LAST:event_botMenuPrincipalActionPerformed

    private void botEstadoTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEstadoTurnosActionPerformed
       
        
    }//GEN-LAST:event_botEstadoTurnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botEstadoTurnos;
    private javax.swing.JButton botMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private ControladorVolverMenuPrincipal controladorRegresar;
    private ControladorMisTurnosProf controladorEstadoTurnoPr;
    
    
}
